// Artifact library — argenx demo.

export const ARTIFACTS = [
  {
    id: 'ART1',
    title: 'Strategy-to-Action — Q2 2026',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-05-30',
    summary: 'Full Q2 Strategy-to-Action: ISP pillars, MO coverage, prioritised insights (AI1–AI5), proposed actions (A1–A9), FcRn competitor differentiation summary, IVIg-to-SC transition signal velocity, Gap Radar suggestions, and CIDP earlier-line LP expansion rationale.',
    dataSources: ['MSL field notes', 'Ad board transcripts', 'Med Info queries', 'X / LinkedIn social listening', 'AAN 2025 congress debriefs', 'PubMed'],
    sizeLabel: '2.4 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART2',
    title: 'AAN / EAN 2025 Debrief — FcRn & SC Modality Signal Analysis',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2026-06-03',
    summary: 'Synthesized read on gMG, CIDP, and FcRn scientific themes at AAN and EAN 2025 — Rystiggo vs Vyvgart Hytrulo social amplification map, KOL post-congress narrative shifts, SC modality share-of-voice, and recommended MSL response actions for competitor differentiation conversations.',
    dataSources: ['AAN 2025 abstracts', 'EAN 2025 session transcripts', 'X / LinkedIn monitoring', 'KOL post-congress commentary'],
    sizeLabel: '2.0 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART3',
    title: 'KOL Public–Private Alignment Report — June 2026',
    type: 'pdf',
    agent: 'LUCA',
    taskType: 'KOL Intelligence Report',
    dateCreated: '2026-06-04',
    summary: 'Alignment scoring for 17 argenx portfolio KOLs across public (X, LinkedIn, Medscape) and private (MSL interaction) channels. Flags 2 divergence cases for immediate action — Dr. Lacomis (IVIg-to-SC scepticism) and Dr. Cockwell (low European engagement). Includes recommended scientific exchange briefs.',
    dataSources: ['MSL interaction logs', 'X / LinkedIn monitoring', 'Medscape / NeurologyLive coverage', 'PubMed publication tracking'],
    sizeLabel: '1.3 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART4',
    title: 'Vyvgart Hytrulo SC Launch Impact — IVIg Transition Baseline Report',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Field Insight Synthesis',
    dateCreated: '2026-05-15',
    summary: 'Baseline measurement of IVIg-to-SC conversion rates, time-to-conversion metrics, and payer site-of-care economics across 28 high-volume gMG and CIDP centers. Key finding: 41% of IV Vyvgart patients are conversion candidates; primary barrier is training infrastructure, not patient preference.',
    dataSources: ['MSL field reports', 'Infusion center utilisation data', 'Patient preference survey (n=214)', 'HEOR model outputs'],
    sizeLabel: '1.8 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART5',
    title: 'FcRn Competitor Landscape — Rystiggo & IMAAVY Differentiation Brief',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Competitive Intelligence Report',
    dateCreated: '2026-05-10',
    summary: 'Head-to-head comparison of efgartigimod (Vyvgart), rozanolixizumab (Rystiggo), and nipocalimab (IMAAVY) across IgG reduction depth, dosing convenience, approved indications, and safety profile. MSL-ready scientific exchange talking points for each differentiation dimension.',
    dataSources: ['Published Phase 3 trial data', 'FDA/EMA approval documents', 'Congress abstract analysis', 'MSL interaction logs'],
    sizeLabel: '1.6 MB',
    provenance: 'synthesized',
  },
];
