// KOL roster — argenx demo.
// gMG / CIDP / ITP + FcRn pipeline pipeline (LN, MN).
// Product IDs: 'vyvgart' | 'vyvgart-hytrulo' | 'empasiprubart'

export const KOL_DATA = [
  {
    id: 'kol-1',
    name: 'Gil Wolfe',
    institution: 'University at Buffalo (SUNY)',
    city: 'Buffalo', country: 'USA', region: 'Northeast',
    specialty: 'Neuromuscular / gMG',
    influenceScore: 96,
    engagementTier: 'Tier 1',
    productAlignment: ['vyvgart', 'vyvgart-hytrulo'],
    recentInteractions: 6,
    publications: 210,
    focusAreas: ['gMG treatment guidelines', 'Antibody-mediated mechanisms', 'CIDP management'],
    conferenceAppearances: ['AAN 2025', 'EAN 2025'],
    recommendedStrategy: 'Advisory board anchor — primary gMG guideline author. Prioritize for SC self-injection confidence data exchange and CIDP earlier-line positioning ahead of AAN 2025 abstract drops.',
    email: '',
  },
  {
    id: 'kol-2',
    name: 'Angela Vincent',
    institution: 'University of Oxford',
    city: 'Oxford', country: 'UK', region: 'Europe',
    specialty: 'Neuroimmunology / gMG',
    influenceScore: 94,
    engagementTier: 'Tier 1',
    productAlignment: ['vyvgart', 'vyvgart-hytrulo'],
    recentInteractions: 4,
    publications: 320,
    focusAreas: ['AChR antibody mechanisms', 'MuSK-MG', 'FcRn biology'],
    conferenceAppearances: ['EAN 2025', 'EFNS'],
    recommendedStrategy: 'Scientific exchange lead on FcRn mechanism differentiation vs Rystiggo/IMAAVY. Leverage Oxford platform for European KOL amplification.',
    email: '',
  },
  {
    id: 'kol-3',
    name: 'Henry Kaminski',
    institution: 'George Washington University',
    city: 'Washington DC', country: 'USA', region: 'Northeast',
    specialty: 'Neurology / gMG',
    influenceScore: 89,
    engagementTier: 'Tier 1',
    productAlignment: ['vyvgart', 'vyvgart-hytrulo'],
    recentInteractions: 5,
    publications: 175,
    focusAreas: ['gMG registry data', 'Real-world outcomes', 'Patient-reported outcomes'],
    conferenceAppearances: ['AAN 2025', 'Myasthenia Gravis Foundation'],
    recommendedStrategy: 'RWE co-author opportunity — real-world registry partnership to strengthen Vyvgart Hytrulo durability narrative.',
    email: '',
  },
  {
    id: 'kol-4',
    name: 'Donald Sanders',
    institution: 'Duke University Medical Center',
    city: 'Durham', country: 'USA', region: 'Southeast',
    specialty: 'Neuromuscular / gMG / CIDP',
    influenceScore: 82,
    engagementTier: 'Tier 2',
    productAlignment: ['vyvgart', 'vyvgart-hytrulo'],
    recentInteractions: 3,
    publications: 130,
    focusAreas: ['Thymectomy outcomes', 'CIDP electrodiagnostics', 'gMG crisis management'],
    conferenceAppearances: ['AAN 2025'],
    recommendedStrategy: 'CIDP earlier-line exchange — Duke has high CIDP referral volume. Schedule before EAN 2025 poster session on ADHERE study.',
    email: '',
  },
  {
    id: 'kol-5',
    name: 'Nicholas Silvestri',
    institution: 'University at Buffalo (SUNY)',
    city: 'Buffalo', country: 'USA', region: 'Northeast',
    specialty: 'Neuromuscular / gMG',
    influenceScore: 78,
    engagementTier: 'Tier 2',
    productAlignment: ['vyvgart-hytrulo'],
    recentInteractions: 4,
    publications: 95,
    focusAreas: ['SC self-injection training', 'Patient adherence', 'gMG burden of disease'],
    conferenceAppearances: ['AAN 2025'],
    recommendedStrategy: 'SC modality champion — high volume SC prescribing at Buffalo. Ideal for patient case studies and self-injection training resource co-development.',
    email: '',
  },
  {
    id: 'kol-6',
    name: 'David Lacomis',
    institution: 'University of Pittsburgh Medical Center',
    city: 'Pittsburgh', country: 'USA', region: 'Northeast',
    specialty: 'Neuromuscular / EMG',
    influenceScore: 76,
    engagementTier: 'Tier 2',
    productAlignment: ['vyvgart', 'vyvgart-hytrulo'],
    recentInteractions: 2,
    publications: 110,
    focusAreas: ['CIDP electrodiagnosis', 'Neuromuscular ultrasound', 'Inflammatory neuropathy'],
    conferenceAppearances: ['AAN 2025', 'AANEM 2025'],
    recommendedStrategy: 'CIDP diagnostic pathway — UPMC referral hub. MSL engagement gap detected (last contact 9 weeks). Re-engage with ADHERE CIDP data package.',
    email: '',
  },
  {
    id: 'kol-7',
    name: 'John Kissel',
    institution: 'The Ohio State University Wexner Medical Center',
    city: 'Columbus', country: 'USA', region: 'Midwest',
    specialty: 'Neuromuscular / CIDP',
    influenceScore: 81,
    engagementTier: 'Tier 2',
    productAlignment: ['vyvgart-hytrulo'],
    recentInteractions: 3,
    publications: 155,
    focusAreas: ['CIDP treatment algorithms', 'Inflammatory myopathy', 'Congenital myasthenia'],
    conferenceAppearances: ['AAN 2025', 'EAN 2025'],
    recommendedStrategy: 'CIDP earlier-line positioning — OSU is a high CIDP volume center. Leverage for Hytrulo CIDP real-world case series.',
    email: '',
  },
  {
    id: 'kol-8',
    name: 'Vera Bril',
    institution: 'University of Toronto',
    city: 'Toronto', country: 'Canada', region: 'Canada',
    specialty: 'Neurology / CIDP / gMG',
    influenceScore: 84,
    engagementTier: 'Tier 2',
    productAlignment: ['vyvgart', 'vyvgart-hytrulo'],
    recentInteractions: 2,
    publications: 140,
    focusAreas: ['CIDP INCAT score outcomes', 'gMG treatment response', 'Canadian neuromuscular RWE'],
    conferenceAppearances: ['EAN 2025', 'AAN 2025'],
    recommendedStrategy: 'Canadian RWE partner — key CIDP trial co-investigator. Opportunity to anchor Hytrulo CIDP Canadian data package.',
    email: '',
  },
  {
    id: 'kol-9',
    name: 'Richard Lewis',
    institution: 'Cedars-Sinai Medical Center',
    city: 'Los Angeles', country: 'USA', region: 'West',
    specialty: 'Neuromuscular / CIDP',
    influenceScore: 80,
    engagementTier: 'Tier 2',
    productAlignment: ['vyvgart-hytrulo'],
    recentInteractions: 3,
    publications: 120,
    focusAreas: ['CIDP peripheral nerve', 'IVIg dependence patterns', 'Nerve conduction studies'],
    conferenceAppearances: ['AAN 2025', 'AANEM 2025'],
    recommendedStrategy: 'IVIg-to-SC transition — Cedars-Sinai has significant IVIg-dependent CIDP cohort. Ideal for transition case studies and payer impact messaging.',
    email: '',
  },
  {
    id: 'kol-10',
    name: 'David Kuter',
    institution: 'Massachusetts General Hospital / Harvard',
    city: 'Boston', country: 'USA', region: 'Northeast',
    specialty: 'Hematology / ITP',
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['vyvgart', 'vyvgart-hytrulo'],
    recentInteractions: 5,
    publications: 280,
    focusAreas: ['ITP pathophysiology', 'TPO-RA therapy', 'FcRn-mediated ITP'],
    conferenceAppearances: ['ASH 2025', 'EHA 2025'],
    recommendedStrategy: 'ITP FcRn mechanism anchor — primary ITP guideline contributor. Prioritize for FcRn differentiation vs nipocalimab (IMAAVY) scientific exchange ahead of ASH 2025.',
    email: '',
  },
  {
    id: 'kol-11',
    name: 'James Bussel',
    institution: 'Weill Cornell Medicine',
    city: 'New York', country: 'USA', region: 'Northeast',
    specialty: 'Pediatric Hematology / ITP',
    influenceScore: 91,
    engagementTier: 'Tier 1',
    productAlignment: ['vyvgart', 'vyvgart-hytrulo'],
    recentInteractions: 4,
    publications: 260,
    focusAreas: ['Chronic ITP management', 'Pediatric ITP', 'IVIG in thrombocytopenia'],
    conferenceAppearances: ['ASH 2025', 'EHA 2025'],
    recommendedStrategy: 'Chronic ITP and pediatric positioning — Bussel has published extensively on chronic ITP treatment sequences. Anchor for pediatric Vyvgart dosing confidence data.',
    email: '',
  },
  {
    id: 'kol-12',
    name: 'Douglas Cines',
    institution: 'University of Pennsylvania',
    city: 'Philadelphia', country: 'USA', region: 'Northeast',
    specialty: 'Hematology / ITP / Autoimmune',
    influenceScore: 88,
    engagementTier: 'Tier 1',
    productAlignment: ['vyvgart'],
    recentInteractions: 3,
    publications: 200,
    focusAreas: ['IgG-mediated platelet destruction', 'HIT', 'Antibody-mediated cytopenias'],
    conferenceAppearances: ['ASH 2025'],
    recommendedStrategy: 'Mechanism differentiation — FcRn biology expertise. Opportunity for advisory board on cross-indication FcRn data and empasiprubart pipeline readout.',
    email: '',
  },
  {
    id: 'kol-13',
    name: 'Sean Pittock',
    institution: 'Mayo Clinic',
    city: 'Rochester', country: 'USA', region: 'Midwest',
    specialty: 'Neuroimmunology / Autoimmune Neurology',
    influenceScore: 79,
    engagementTier: 'Tier 2',
    productAlignment: ['vyvgart', 'empasiprubart'],
    recentInteractions: 2,
    publications: 145,
    focusAreas: ['NMOSD', 'Autoimmune encephalitis', 'Antibody biomarkers'],
    conferenceAppearances: ['AAN 2025', 'EAN 2025'],
    recommendedStrategy: 'Pipeline bridge — Mayo neuroimmunology volume and NMOSD pipeline relevance. Early empasiprubart engagement ahead of Phase 3 readout.',
    email: '',
  },
  {
    id: 'kol-14',
    name: 'Brad Rovin',
    institution: 'The Ohio State University Wexner Medical Center',
    city: 'Columbus', country: 'USA', region: 'Midwest',
    specialty: 'Nephrology / Lupus Nephritis',
    influenceScore: 90,
    engagementTier: 'Tier 1',
    productAlignment: ['empasiprubart'],
    recentInteractions: 3,
    publications: 190,
    focusAreas: ['Lupus nephritis clinical trials', 'IgA nephropathy', 'FcRn in renal disease'],
    conferenceAppearances: ['ASN 2025', 'ERA 2025'],
    recommendedStrategy: 'Lupus nephritis pipeline — OSU is a primary trial site for FcRn agents in LN. Secure Rovin for empasiprubart scientific advisory role ahead of ASN 2025.',
    email: '',
  },
  {
    id: 'kol-15',
    name: 'Fernando Fervenza',
    institution: 'Mayo Clinic',
    city: 'Rochester', country: 'USA', region: 'Midwest',
    specialty: 'Nephrology / Membranous Nephropathy',
    influenceScore: 87,
    engagementTier: 'Tier 1',
    productAlignment: ['empasiprubart'],
    recentInteractions: 2,
    publications: 170,
    focusAreas: ['Membranous nephropathy', 'PLA2R antibody', 'FcRn-mediated glomerular disease'],
    conferenceAppearances: ['ASN 2025', 'ISN 2025'],
    recommendedStrategy: 'MN FcRn pipeline anchor — leading MN researcher with direct interest in FcRn reduction of PLA2R-IgG. Key for empasiprubart Phase 3 enrollment and publication strategy.',
    email: '',
  },
  {
    id: 'kol-16',
    name: 'Susan Manzi',
    institution: 'Allegheny Health Network',
    city: 'Pittsburgh', country: 'USA', region: 'Northeast',
    specialty: 'Rheumatology / Lupus',
    influenceScore: 83,
    engagementTier: 'Tier 1',
    productAlignment: ['empasiprubart'],
    recentInteractions: 2,
    publications: 160,
    focusAreas: ['Systemic lupus erythematosus', 'Lupus nephritis outcomes', 'Patient quality of life in SLE'],
    conferenceAppearances: ['ACR 2025', 'EULAR 2025'],
    recommendedStrategy: 'SLE pipeline rheumatology voice — Manzi is the bridge between rheumatology and nephrology in LN management. Prioritize for empasiprubart patient outcomes narrative.',
    email: '',
  },
  {
    id: 'kol-17',
    name: 'Paul Cockwell',
    institution: 'University Hospitals Birmingham NHS Trust',
    city: 'Birmingham', country: 'UK', region: 'Europe',
    specialty: 'Nephrology / ANCA Vasculitis',
    influenceScore: 77,
    engagementTier: 'Tier 2',
    productAlignment: ['empasiprubart'],
    recentInteractions: 1,
    publications: 130,
    focusAreas: ['ANCA-associated vasculitis', 'Glomerulonephritis', 'Renal outcomes'],
    conferenceAppearances: ['ERA 2025', 'BSR 2025'],
    recommendedStrategy: 'European nephrology pipeline — low engagement (last contact 11 weeks). Re-engage ahead of ERA 2025 with empasiprubart European regulatory pathway update.',
    email: '',
  },
];
