// Predictive Signals — Command Center & NOVA — argenx demo.
// Each signal carries an agent attribution (which agent surfaced it) plus
// trajectory / confidence / time-to-impact framing.

export const PREDICTIVE_SIGNALS = [
  {
    id: 'ps-1',
    agent: 'NOVA',
    signal: 'IV→SC Hytrulo conversion inertia crossing recurrence threshold',
    currentState: 'Insight AI1 recorded a fourth source this month — now at Prioritised status. Strategy-to-Action recommends a community-facing conversion narrative as the flagship MO1 deliverable.',
    trajectory: 'rising',
    timeToImpact: '0–6 months',
    confidence: 'high',
    requiredAction: 'Approve the community-facing SC conversion narrative; deploy to the MSL field team.',
    suggestedAction: { label: 'Open in NOVA', path: '/insights' },
  },
  {
    id: 'ps-2',
    agent: 'ARIA',
    signal: 'Competitor symposium added at AAN follow-up congress (Rystiggo CIDP data)',
    currentState: 'UCB has added a late-breaking Rystiggo CIDP readout session. No equivalent argenx session is currently scheduled in that room.',
    trajectory: 'rising',
    timeToImpact: '0–3 months',
    confidence: 'high',
    requiredAction: 'Brief MSL team before the session. Prepare CIDP differentiation talking points and a Q4W-vs-Q2W dosing one-pager.',
    suggestedAction: { label: 'Open in ARIA', path: '/congress' },
  },
  {
    id: 'ps-3',
    agent: 'LUCA',
    signal: 'Sentiment shift: Dr. David Lacomis softening on CIDP earlier-line positioning',
    currentState: 'Two recent congress talks and one advisory board comment show reduced enthusiasm for first-line FcRn positioning in CIDP compared to 60 days ago — a public/private divergence LUCA is flagging as urgent.',
    trajectory: 'declining',
    timeToImpact: '3–6 months',
    confidence: 'medium',
    requiredAction: 'Schedule a 1:1 scientific exchange; bring the updated ADHERE post-hoc treatment-naïve data.',
    suggestedAction: { label: 'Open in LUCA', path: '/kol' },
  },
  {
    id: 'ps-4',
    agent: 'NOVA',
    signal: 'Home self-injection training gap recurrence threshold hit',
    currentState: 'Insight AI4 recorded a third source this month — now Validated. NOVA recommends the home-injection confidence toolkit as the flagship co-created MO1 deliverable.',
    trajectory: 'rising',
    timeToImpact: '3–6 months',
    confidence: 'high',
    requiredAction: 'Approve the patient + HCP self-injection toolkit; deploy to the top infusion-to-home accounts.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
  {
    id: 'ps-5',
    agent: 'LUCA',
    signal: '2 emerging pipeline KOLs crossed the watch threshold',
    currentState: 'Publication cadence and congress-speaking frequency on complement-mediated glomerular disease are up 45% vs the prior 6 months for two nephrology/rheumatology investigators. Neither is currently on the empasiprubart engagement list.',
    trajectory: 'rising',
    timeToImpact: '3–6 months',
    confidence: 'medium',
    requiredAction: 'Add both to the LUCA watch list; assign an MSL for initial outreach ahead of the Phase 3 readout window.',
    suggestedAction: { label: 'Open in LUCA', path: '/kol' },
  },
];
